/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roomshare;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import sun.tools.jconsole.AboutDialog;


/**
 *
 * @author MI2
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        about2 = new javax.swing.JLabel();
        ig2 = new javax.swing.JLabel();
        te2 = new javax.swing.JLabel();
        wt2 = new javax.swing.JLabel();
        fb2 = new javax.swing.JLabel();
        db2 = new javax.swing.JLabel();
        call2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(100, 100));

        about2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-48.png"))); // NOI18N
        about2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about2MouseExited(evt);
            }
        });
        jLayeredPane1.add(about2);
        about2.setBounds(600, 10, 50, 50);

        ig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/instagram64 .png"))); // NOI18N
        ig2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ig2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ig2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ig2MouseExited(evt);
            }
        });
        jLayeredPane1.add(ig2);
        ig2.setBounds(670, 350, 60, 50);

        te2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/telegram64.png"))); // NOI18N
        te2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                te2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                te2MouseExited(evt);
            }
        });
        jLayeredPane1.add(te2);
        te2.setBounds(670, 280, 60, 64);

        wt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/whatsapp64.png"))); // NOI18N
        wt2.setText("jLabel5");
        wt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wt2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wt2MouseExited(evt);
            }
        });
        jLayeredPane1.add(wt2);
        wt2.setBounds(670, 210, 60, 60);

        fb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/facebook64.png"))); // NOI18N
        fb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fb2MouseExited(evt);
            }
        });
        jLayeredPane1.add(fb2);
        fb2.setBounds(670, 140, 60, 60);

        db2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbb.png"))); // NOI18N
        db2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                db2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db2MouseExited(evt);
            }
        });
        jLayeredPane1.add(db2);
        db2.setBounds(670, 70, 60, 60);

        call2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/call.png"))); // NOI18N
        call2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                call2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                call2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                call2MouseExited(evt);
            }
        });
        jLayeredPane1.add(call2);
        call2.setBounds(680, 10, 50, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gfgf.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void call2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_call2MouseClicked
        // TODO add your handling code here:
         callus callus1 = new callus();
         callus1.setVisible(true);
         callus1.setDefaultCloseOperation(callus.DISPOSE_ON_CLOSE);
         callus1.setResizable(false);
    }//GEN-LAST:event_call2MouseClicked

    private void ig2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig2MouseClicked
        // TODO add your handling code here:
         instagram instagram1 = new instagram();
        instagram1.setVisible(true);
            instagram1.setDefaultCloseOperation(instagram.DISPOSE_ON_CLOSE);
            instagram1.setResizable(false);
    }//GEN-LAST:event_ig2MouseClicked

    private void db2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db2MouseClicked
 roomdata roomdata1 = new roomdata();
        roomdata1.setVisible(true);
        roomdata1.setDefaultCloseOperation(roomdata.DISPOSE_ON_CLOSE);
        roomdata1.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_db2MouseClicked

    private void fb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fb2MouseClicked
        // TODO add your handling code here:
         facebook facebook1 = new facebook();
        facebook1.setResizable(false);
        
        

        
        
        
        facebook1.setVisible(true);
    facebook1.setDefaultCloseOperation(facebook.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_fb2MouseClicked

    private void wt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wt2MouseClicked
 whatsapp whatsapp1 = new whatsapp();
       whatsapp1.setVisible(true);
                whatsapp1.setDefaultCloseOperation(whatsapp.DISPOSE_ON_CLOSE);
               whatsapp1.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_wt2MouseClicked

    private void te2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te2MouseClicked
 telegram telegram1 = new telegram();
         telegram1.setVisible(true);
         telegram1.setDefaultCloseOperation(telegram1.DISPOSE_ON_CLOSE);
       telegram1.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_te2MouseClicked

    private void about2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about2MouseClicked
 
        about about1 = new about();
        about1.setVisible(true);
            about1.setDefaultCloseOperation(about.DISPOSE_ON_CLOSE);
            about1.setResizable(false);        // TODO add your handling code here:
    }//GEN-LAST:event_about2MouseClicked

    private void about2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about2MouseEntered
        // TODO add your handling code here:
        
        


        about2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/about2.png ")));
        
        
        
    }//GEN-LAST:event_about2MouseEntered

    private void about2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about2MouseExited
        // TODO add your handling code here:
        about2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-48.png ")));
    }//GEN-LAST:event_about2MouseExited

    private void call2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_call2MouseEntered
        // TODO add your handling code here:
        call2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/call2.png ")));
    }//GEN-LAST:event_call2MouseEntered

    private void db2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db2MouseEntered
        // TODO add your handling code here:
        db2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbb2.png ")));
    }//GEN-LAST:event_db2MouseEntered

    private void call2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_call2MouseExited
        // TODO add your handling code here:
                call2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/call.png ")));

    }//GEN-LAST:event_call2MouseExited

    private void db2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db2MouseExited
        // TODO add your handling code here:
                db2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/dbb.png ")));

    }//GEN-LAST:event_db2MouseExited

    private void fb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fb2MouseEntered
        // TODO add your handling code here:
                fb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/facebook2.png ")));

    }//GEN-LAST:event_fb2MouseEntered

    private void fb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fb2MouseExited
        // TODO add your handling code here:
                fb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/facebook64.png")));

    }//GEN-LAST:event_fb2MouseExited

    private void wt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wt2MouseEntered
        // TODO add your handling code here:
                wt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/whatsapp2.png ")));

    }//GEN-LAST:event_wt2MouseEntered

    private void wt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wt2MouseExited
        // TODO add your handling code here:
                wt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/whatsapp64.png ")));

    }//GEN-LAST:event_wt2MouseExited

    private void te2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te2MouseEntered
        // TODO add your handling code here:
                te2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/telegram2.png ")));

    }//GEN-LAST:event_te2MouseEntered

    private void te2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te2MouseExited
        // TODO add your handling code here:
                        te2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/telegram64.png ")));

    }//GEN-LAST:event_te2MouseExited

    private void ig2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig2MouseEntered
        // TODO add your handling code here:
                        ig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/instagram2.png ")));

    }//GEN-LAST:event_ig2MouseEntered

    private void ig2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ig2MouseExited
        // TODO add your handling code here:
                        ig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/instagram64.png ")));

    }//GEN-LAST:event_ig2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel about2;
    private javax.swing.JLabel call2;
    private javax.swing.JLabel db2;
    private javax.swing.JLabel fb2;
    private javax.swing.JLabel ig2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel te2;
    private javax.swing.JLabel wt2;
    // End of variables declaration//GEN-END:variables

    void setHorizontalAlignment(int CENTER) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setExtendedState(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
